version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: cloud-library-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: zuosi233
      MYSQL_DATABASE: cloud_library
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
'
