services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=cloud_library'
      - 'MYSQL_PASSWORD=zuosi233'
      - 'MYSQL_ROOT_PASSWORD=zuosi233'
      - 'MYSQL_USER=root'
    ports:
      - '3306'
